//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Chat
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conversations()
        {
            this.messages = new HashSet<messages>();
        }
    
        public int id { get; set; }
        public Nullable<int> last_message_id { get; set; }
        public int first_participant { get; set; }
        public int second_participant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messages> messages { get; set; }
        public virtual users users1 { get; set; }
        public virtual users users11 { get; set; }
    }
}
